
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssamctnybxlvwrrlfbmz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzYW1jdG55YnhsdndycmxmYm16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkzNDYxMzUsImV4cCI6MjA1NDkyMjEzNX0.qyr63Do8EbDwuRSsNmYCy4ay9b8r-OfrKohCkTZAduM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    db: {
      schema: 'public',
    },
    global: {
      headers: {
        'x-application-name': 'student-question-app',
      },
    },
  }
);

// Add debugging helper to log database responses in development
if (import.meta.env.DEV) {
  // Log every Supabase response in development to help debug
  const originalFrom = supabase.from.bind(supabase);
  supabase.from = function(table) {
    const result = originalFrom(table);
    
    // Wrap select method to add logging
    const originalSelect = result.select.bind(result);
    result.select = function(...args) {
      const query = originalSelect(...args);
      
      const originalThen = query.then.bind(query);
      query.then = function(onFulfilled, onRejected) {
        return originalThen(
          (data) => {
            console.log(`[Supabase Debug] ${table} select response:`, data);
            return onFulfilled?.(data);
          },
          onRejected
        );
      };
      
      return query;
    };
    
    return result;
  };
}
